//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaColaborativos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservacion()
        {
            this.factura = new HashSet<factura>();
            this.reservacion_has_silla = new HashSet<reservacion_has_silla>();
        }
    
        public int id_reservacion { get; set; }
        public bool estado_reservacion { get; set; }
        public int usuario_id_usuario { get; set; }
        public int proyeccion_id_proyeccion { get; set; }
        public int proyeccion_pelicula_id_pelicula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        public virtual pelicula pelicula { get; set; }
        public virtual proyeccion proyeccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservacion_has_silla> reservacion_has_silla { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
